/// Receives tokens generated by the backend during decoding.
public protocol TokenStreamDelegate: AnyObject {
    /// Called when a new token is produced.
    /// - Parameter token: The newly generated token ID.
    func didGenerate(token: Int32)
}
