name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: '6.1'
      - name: Build and test
        run: |
          xcodebuild -scheme LilimsApp -destination 'generic/platform=iOS Simulator' test
