name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.1.app
      - name: Build and test
        run: |
          xcodebuild -scheme LilimsApp -destination 'generic/platform=iOS Simulator' test
