name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Cache Nix store
        uses: cachix/cachix-action@v16
        with:
          name: forketyfork
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build and tes
        run: |
          nix develop --command bash -c '
            swift test
          '
