name: Python Scripts

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Run scripts
        run: python Scripts/hello.py
